INPUT:
  SIZE: (224, 224)
  TRANSFORMS: ["random_flip", "random_translation", "normalize"]

DATASET:
  NAME: "SSDGMiniDomainNet"
  NUM_LABELED: 3780 # 10 for each source domain

MODEL:
  BACKBONE:
    NAME: "resnet18"
    PRETRAINED: True